/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorLogin;
import controlador.ControladorUsuario;

/**
 *
 * @author Martin
 */
public class RegistroFrm extends javax.swing.JFrame {

    /**
     * Creates new form RegistroFrm
     */
    public RegistroFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jcbTipoUsuario = new javax.swing.JComboBox<>();
        btnRegiatrarse = new javax.swing.JButton();
        lbNotify = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(33, 59, 16));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 179, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 6, 170, 36));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Users\\Martin\\Desktop\\Martin\\Universidad\\Segundo Nivel\\Programacion orientada a objetos\\Proyectos_java\\AgroquimicosApp\\src\\Imagenes\\icons8_name_50px.png")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, 49, 41));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Users\\Martin\\Desktop\\Martin\\Universidad\\Segundo Nivel\\Programacion orientada a objetos\\Proyectos_java\\AgroquimicosApp\\src\\Imagenes\\icons8_email_50px.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 342, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(73, 179, 24));
        jLabel3.setText("NOMBRE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 60, -1, -1));

        jLabel4.setBackground(new java.awt.Color(73, 179, 24));
        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(73, 179, 24));
        jLabel4.setText("APELLIDO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel5.setBackground(new java.awt.Color(73, 179, 24));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(73, 179, 24));
        jLabel5.setText("NOMBRE DE USUARIO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(73, 179, 24));
        jLabel6.setText("CONTRASEÑA");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        txtCorreo.setBackground(new java.awt.Color(33, 59, 16));
        txtCorreo.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setBorder(null);
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 225, 20));

        txtApellido.setBackground(new java.awt.Color(33, 59, 16));
        txtApellido.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setBorder(null);
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 152, 225, 20));

        txtNombreUsuario.setBackground(new java.awt.Color(33, 59, 16));
        txtNombreUsuario.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtNombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreUsuario.setBorder(null);
        jPanel2.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 222, 225, 20));

        txtNombre.setBackground(new java.awt.Color(33, 59, 16));
        txtNombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(null);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 82, 225, 20));

        txtContraseña.setBackground(new java.awt.Color(33, 59, 16));
        txtContraseña.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(0, 0, 0));
        txtContraseña.setBorder(null);
        jPanel2.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 292, 225, 20));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(73, 179, 24));
        jLabel7.setText("CORREO ELECTRONICO");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(73, 179, 24));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 322, 225, 10));

        jSeparator2.setBackground(new java.awt.Color(73, 179, 24));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 225, 10));

        jSeparator3.setBackground(new java.awt.Color(73, 179, 24));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 252, 225, 10));

        jSeparator4.setBackground(new java.awt.Color(73, 179, 24));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 182, 225, 10));

        jSeparator5.setForeground(new java.awt.Color(73, 179, 24));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 112, 225, 10));

        jPanel1.setBackground(new java.awt.Color(33, 59, 16));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(73, 179, 24));
        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(73, 179, 24));
        jLabel9.setText("ESCOGA EL TIPO DE USUARIO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jcbTipoUsuario.setBackground(new java.awt.Color(33, 59, 16));
        jcbTipoUsuario.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jcbTipoUsuario.setForeground(new java.awt.Color(73, 179, 24));
        jcbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Comprador" }));
        jcbTipoUsuario.setBorder(null);
        jPanel1.add(jcbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 70, 190, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 250, 160));

        btnRegiatrarse.setBackground(new java.awt.Color(33, 59, 16));
        btnRegiatrarse.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnRegiatrarse.setForeground(new java.awt.Color(73, 179, 24));
        btnRegiatrarse.setText("REGISTRARSE");
        btnRegiatrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegiatrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegiatrarseActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegiatrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 140, 30));

        lbNotify.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbNotify.setForeground(new java.awt.Color(73, 179, 24));
        jPanel2.add(lbNotify, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegiatrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegiatrarseActionPerformed
        //ControladorUsuario c = new ControladorUsuario();
        
        
    }//GEN-LAST:event_btnRegiatrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        RegistroFrm g = new RegistroFrm();
        ControladorUsuario c = new ControladorUsuario(g);
        g.setVisible(true);
        g.setLocationRelativeTo(g);
        
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegiatrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JComboBox<String> jcbTipoUsuario;
    public javax.swing.JLabel lbNotify;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtContraseña;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
